fpath=(~/.nix-profile/share/zsh/site-function $fpath)

export XDG_RUNTIME_DIR=~/.local/run
export XDG_DATA_HOME=~/.local/share
export XDG_STATE_HOME=~/.local/state
export XDG_CONFIG_HOME=~/.config
export XDG_CACHE_HOME=~/.cache

export ZDOTDIR=$XDG_CONFIG_HOME/zsh
export WGETRC=$XDG_CONFIG_HOME/wget/wgetrc
export LESSHISTFILE=$XDG_CACHE_HOME/lesshst
export IPYTHONDIR=$XDG_CONFIG_HOME/ipython

export WEECHAT_HOME=$XDG_CONFIG_HOME/weechat
export XINITRC=$XDG_CONFIG_HOME/x/xinitrc
export XAUTHORITY=$XDG_RUNTIME_DIR/Xauthority
export QT_AUTO_SCREEN_SCALE_FACTOR=0
